# Generated by Django 5.1.7 on 2025-03-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inputdata',
            old_name='contact_no',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='inputdata',
            old_name='github_url',
            new_name='github',
        ),
        migrations.RenameField(
            model_name='inputdata',
            old_name='linkedin_url',
            new_name='linkedin',
        ),
        migrations.RemoveField(
            model_name='inputdata',
            name='manual_text',
        ),
        migrations.AlterField(
            model_name='inputdata',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
